######################################################################
# Automatically generated by qmake (3.0) Tue Oct 29 11:15:25 2019
######################################################################

TEMPLATE = app
TARGET = nui
INCLUDEPATH += .

# Input
SOURCES += main.cpp FileReader.cpp Unlogger.cpp
HEADERS = FileReader.hpp Unlogger.hpp

CONFIG += c++14

QT += widgets network core

INCLUDEPATH += /home/batman/one/phonelibs/capnp-cpp/include /home/batman/one /home/batman/one/selfdrive/messaging /home/batman/one/phonelibs/yaml-cpp/include
LIBS += -lbz2 -L/home/batman/one/phonelibs/capnp-cpp/x64/lib -l:libcapnp.a -l:libkj.a -L/home/batman/one/selfdrive/messaging -l:messaging.a -L/home/batman/one/phonelibs/yaml-cpp/x64/lib -l:libyaml-cpp.a

